### ISSUE TITLE
Lots of runtime errors

### ISSUE THREAD

**Issue by mohammad-reza-sasani** [anandpawara/Real_Time_Image_Animation#43]
hi 
i always use python in django 
And I do not have much information about artificial intelligence and image processing
And I installed all the modules and deleted the files you mentioned
But while running, I encountered these errors
I really need this project
please help
erros 
-------------
PS D:\Programmer\python\Real_Time_Image_Animation-master> python .\image_animation.py -i .\Inputs\Monalisa.png -c .\checkpoints\vox-cpk.pth.tar    
[INFO] loading source image and checkpoint...
C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\transform\_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\transform\_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
D:\Programmer\python\Real_Time_Image_Animation-master\demo.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
Traceback (most recent call last):
  File ".\image_animation.py", line 32, in <module>
    generator, kp_detector = load_checkpoints(config_path='config/vox-256.yaml', checkpoint_path=checkpoint_path)
  File "D:\Programmer\python\Real_Time_Image_Animation-master\demo.py", line 32, in load_checkpoints
    generator.cuda()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 491, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 387, in _apply
    module._apply(fn)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 387, in _apply
    module._apply(fn)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 387, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 409, in _apply
    param_applied = fn(param)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 491, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\cuda\__init__.py", line 164, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by mscs4242** [comment]
I want checkpoint.zip file, can you send me that.
